<?php


/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Professional End User
 * License Agreement ('License') which can be viewed at
 * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 * All copies of the Covered Code must include on each user interface screen:
 * (i) the 'Powered by SugarCRM' logo and
 * (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2005 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
/*********************************************************************************
* File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
*********************************************************************************/
/*********************************************************************************
* $Header: /modules/Home/Dashlets/JotPadDashlet/JotPadDashlet.en_us.lang.php,  Wed 28/11/07 18:09:08
* Description : .
* Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
* Contributor(s):
*********************************************************************************/

/*********************************************************************************
* Translation by Madcap - http://www.madcap.nl
* Released under GPL 3
*********************************************************************************/

if (!defined('sugarEntry') || !sugarEntry)
  die('Not A Valid Entry Point');

$defaultText =<<<EOQ
Welkom bij Sugar 5.0<br /><br />

De laatste wijzigingen:<br />
* Betere Dashboard grafieken<br />
* Nieuwe e-mail client voor betere communicatie<br />
* Module Builder om uw eigen modules te maken<br />
* Verbeterde Studio om uw SugarCRM aan te passen<br /><br />

Voor meer informatie, ga naar de Sugar University.<br />
EOQ;

$dashletStrings['JotPadDashlet'] = array (
  'LBL_TITLE' => 'JotPad',
  'LBL_DESCRIPTION' => 'Een Dashlet voor uw notities',
  'LBL_SAVING' => 'JotPad opslaan...',
  'LBL_SAVED' => 'Opgeslagen',
  'LBL_CONFIGURE_TITLE' => 'Titel',
  'LBL_CONFIGURE_HEIGHT' => 'Hoogte (1 - 300)',
  'LBL_DBLCLICK_HELP' => 'Dubbelklik hieronder om te wijzigen.',
  'LBL_DEFAULT_TEXT' => $defaultText,

);
?>